# Generated by Django 6.0.6 on 2026-06-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='temp123', max_length=255),
            preserve_default=False,
        ),
    ]
