# Generated by Django 6.0.6 on 2026-07-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='company_location',
            new_name='domain',
        ),
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.CharField(default='Not specified', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_salary',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_size',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
