# Generated by Django 6.0.6 on 2026-07-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_job_salary_job_created_at_job_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
