# Generated by Django 6.0.6 on 2026-07-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_job_is_featured'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='core_job_status_4b2344_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location'], name='core_job_locatio_a1880e_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_type'], name='core_job_job_typ_5d260f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['experience'], name='core_job_experie_1e4e55_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['salary_min', 'salary_max'], name='core_job_salary__b1b42a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-created_at'], name='core_job_created_e0bc94_idx'),
        ),
    ]
